let product = [
  {
    id: 1,
    title: "Dunk Low Retro",
    category: "Sneakers",
    imgUrl: "pic/1.jpg",
    price: 100,
  },
  {
    id: 2,
    title: "Air Force 1 07",
    category: "Derby shoes",
    imgUrl: "pic/2.jpg",
    price: 200,
  },
  {
    id: 3,
    title: "Nike Dunk Low Grey",
    category: "Sailing shoes",
    imgUrl: "pic/3.jpg",
    price: 300,
  },
  {
    id: 4,
    title: "Air Max 270",
    category: "Air Yeezy",
    imgUrl: "pic/4.jpg",
    price: 150,
  },
  {
    id: 5,
    title: "Kratter Impact",
    category: "Flywire",
    imgUrl: "pic/5.jpg",
    price: 120,
  },
  {
    id: 6,
    title: "Dunk Low Burgundy",
    category: "Terminator",
    imgUrl: "pic/6.jpg",
    price: 190,
  },
  {
    id: 7,
    title: "P-6000 Light Iron'",
    category: "Monk shoe",
    imgUrl: "pic/7.jpg",
    price: 350,
  },
  {
    id: 8,
    title: "Air Pegasus White",
    category: "Diabetic shoe",
    imgUrl: "pic/8.jpg",
    price: 230,
  },
  {
    id: 9,
    title: "Hot Step Air Terra",
    category: "Earth shoe",
    imgUrl: "pic/9.jpg",
    price: 320,
  },
];
